name: Test unit tests Robert
on:
  pull_request: 
    branch: 
      - main

jobs: 
  setup-deploy:
    name: Install and Run
    runs-on: ubuntu-latest

  steps:
    - name: Check-out
      uses: actions/checkout@v3

    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pytest
      id: requirements
      run: |
          python -m pip install --upgrade pip
          pip install pytest
    
    - name: Run tests
      run: |
          pytest -q src